Numpy array and basics


In [1]:
import numpy as np


Array creation

In [6]:
#1d Array creations
arr_1d=np.array([10,20,30,40])
print(arr_1d,type(arr_1d)) 
#2d array
arr_2d=np.array([[10,20,30],[40,50,60]])
print(arr_2d)

[10 20 30 40] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]


List v/s Numpy Array

In [ ]:
#Approach 1
cost_list=[10,20,30,40]
print("Selling List",cost_list*2) #Not possible
cost_arr=np.array([10,20,30,40])
print("Selling Arr",cost_arr*2)
#Approach 2
d1_list=[10,20,30,40]
d2_list=[20,15,45,50]
print("Total sale",d1_list+d2_list) #Not possible
d1_Arr=np.array([10,20,30,40])
d2_Arr=np.array([20,15,45,50])
print("Total sale",d1_Arr+d2_Arr)

Selling List [10, 20, 30, 40, 10, 20, 30, 40]
Selling Arr [20 40 60 80]
Total sale [10, 20, 30, 40, 20, 15, 45, 50]
Total sale [30 35 75 90]


In [4]:
import time as t
import numpy as np
#List
start =t.time()
list_time=[i*2 for i in range(10)]
end=t.time()
print("List Operation:",end-start)
#Numpy Array
start=t.time()
arr_time=np.arange(1000000)*2
end=t.time()
print("Array Operation:",end-start)

List Operation: 0.0003559589385986328
Array Operation: 0.004738330841064453


Creating array from Scratch

In [8]:
#Zeros
zeros=np.zeros((2,3))
print("zeros:\n",zeros)
#Ones
ones=np.ones((3,2))
print("Ones Matrix:\n",ones)
#Full
full=np.full((3,3),7)
print("Full with num matrix:\n",full)
#Random
random =np.random.random((2,2))
print("Random matrix(0 to 1):\n",random)
#Sequence start,stop,step
seq=np.arange(10,31)
print("Sequence of 10 to 30:",seq)


zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Full with num matrix:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Random matrix(0 to 1):
 [[0.77341592 0.45463388]
 [0.5853046  0.83551194]]
Sequence of 10 to 30: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


Vector,Matrix and Tensor

In [11]:
vector=np.array([10,20,30,40])
print("Vector:\n",vector)
matrix=np.array([[10,20,30],
                [40,50,60]])
print("Matrix :\n",matrix)
tensor=np.array([
    [[1,2,3],[4,5,6]],
     [[7,8,9],[10,11,12]]
])
print("Tensor:\n",tensor)

Vector:
 [10 20 30 40]
Matrix :
 [[10 20 30]
 [40 50 60]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Array Properties

In [12]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape:",arr.shape)
print("Dimesion:",arr.ndim)
print("Size:",arr.size)
print("DType",arr.dtype)


Shape: (2, 3)
Dimesion: 2
Size: 6
DType int64


Array Reshaping

In [18]:
arr=np.arange(12)
print("array:",arr)
reshape=arr.reshape((4,3))
print("reshape:\n",reshape)
mat=np.array([[10,20,30],
             [40,50,60]])
f1=mat.flatten()
print(f1)

array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshape:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[10 20 30 40 50 60]
