Numpy array and basics


In [1]:
import numpy as np


Array creation

In [6]:
#1d Array creations
arr_1d=np.array([10,20,30,40])
print(arr_1d,type(arr_1d)) 
#2d array
arr_2d=np.array([[10,20,30],[40,50,60]])
print(arr_2d)

[10 20 30 40] <class 'numpy.ndarray'>
[[10 20 30]
 [40 50 60]]


List v/s Numpy Array

In [ ]:
#Approach 1
cost_list=[10,20,30,40]
print("Selling List",cost_list*2) #Not possible
cost_arr=np.array([10,20,30,40])
print("Selling Arr",cost_arr*2)
#Approach 2
d1_list=[10,20,30,40]
d2_list=[20,15,45,50]
print("Total sale",d1_list+d2_list) #Not possible
d1_Arr=np.array([10,20,30,40])
d2_Arr=np.array([20,15,45,50])
print("Total sale",d1_Arr+d2_Arr)

Selling List [10, 20, 30, 40, 10, 20, 30, 40]
Selling Arr [20 40 60 80]
Total sale [10, 20, 30, 40, 20, 15, 45, 50]
Total sale [30 35 75 90]
