Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50])
print("basic slicing:",arr[:4])
print("slicing with step:",arr[0:5:2])
print("Negetive Index:",arr[-1])

basic slicing: [10 20 30 40]
slicing with step: [10 30 50]
Negetive Index: 50


In [13]:
arr_2d=np.array([[1,2,3,10],
                [4,5,6,20],
                [7,8,9,30]])
print("Specific element:",arr_2d[1,2])
print("Entire row:\n",arr_2d[1,:])
print("Entire col:\n",arr_2d[:,1])


Specific element: 6
Entire row:
 [ 4  5  6 20]
Entire col:
 [2 5 8]


Sorting

In [ ]:
arr_1d=np.array([3,5,2,9,5,6,1,7])
print("sorting 1d array",sorted(arr_1d))
print("sorting 1d array",np.sort(arr_1d))
arr_2d=np.array([[2,1],
                [3,2],
                [4,3]])
#axis=0 for col axis=1 ->row
print("sort 2d array\n",np.sort(arr_2d,axis=0))

sorting 1d array [np.int64(1), np.int64(2), np.int64(3), np.int64(5), np.int64(5), np.int64(6), np.int64(7), np.int64(9)]
sorting 1d array [1 2 3 5 5 6 7 9]
sort 2d array
 [[2 1]
 [3 2]
 [4 3]]


Filter

In [18]:
number=np.array([3,5,2,9,5,6,1,7])
even_number=number[number%2==0]
print("Even number:",even_number)

Even number: [2 6]


Filter with mask

In [19]:
marks=np.array([67,34,10,23,50,97,54])
mask_pass=marks>35
print("More the 35(Mask):",mask_pass)

More the 35(Mask): [ True False False False  True  True  True]


Index

In [22]:
sales=np.array([25000,12000,65000,80000])
idc=[1,3]
res=sales[idc]
print("Find value from index:",res)

Find value from index: [12000 80000]


Join

In [3]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
combined=np.concatenate([arr1,arr2])
print("Combined:",combined)

Combined: [ 1  2  3  4 10 20 30 40]


In [4]:
matrix=np.array([[10,20],
                [30,40]])
newmatrix=np.array([[50,60],
                     [70,80]])
print("Join Horizantal:\n",np.hstack([matrix,newmatrix]))
print("Join Vertical:\n",np.vstack([matrix,newmatrix]))

Join Horizantal:
 [[10 20 50 60]
 [30 40 70 80]]
Join Vertical:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]


Adding & Removing

In [6]:
arr=np.array([1,2,3,4,5,6])
print("Split:",np.split(arr,2))
print("Append:",np.append(arr,50))
print("Insert:",np.insert(arr,0,90))
print("Remove",np.delete(arr,2))
print("Org:",arr)

Split: [array([1, 2, 3]), array([4, 5, 6])]
Append: [ 1  2  3  4  5  6 50]
Insert: [90  1  2  3  4  5  6]
Remove [1 2 4 5 6]
Org: [1 2 3 4 5 6]
